[package]
name = "div-int-procmacro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
litrs = "0.4.1"
proc-macro-error = { version = "1.0", default-features = false }
proc-macro2 = "1.0"

[dev-dependencies]
assert_matches = "1.5.0"
div-int = {path ="../div-int"}
